name: fitness_tracker_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Manage widgets Life cycle more efficiently
  flutter_hooks: ^0.20.5

  # hooks and riverpod in one package(pretty cool right?)
  hooks_riverpod: ^2.5.1

  # Navigation, snackbars, dialogs, etc.
  get: ^4.6.6

  # Working with Date/Time
  intl: ^0.19.0

  # State management
  flutter_riverpod: ^2.5.1

  # Animated page indicator
  smooth_page_indicator: ^1.1.0

  # Add svgs to the app
  flutter_svg: ^2.0.10+1

  # Import ready-made animations
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  build_runner: ^2.4.8

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/pngs/app-logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

# flutter_native_splash:
#   background_image: assets/pngs/splashscreen.png
#   android: true
#   ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
